// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjRX5HT-7dpN_--M_UlVv_vNKos6JJN4k',
    appId: '1:254942302329:web:eaa8af1d93f43cb9be44a8',
    messagingSenderId: '254942302329',
    projectId: 'chatapp-a7453',
    authDomain: 'chatapp-a7453.firebaseapp.com',
    storageBucket: 'chatapp-a7453.appspot.com',
    measurementId: 'G-HCK0NEMRBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3gAcHo4jG873zBxxm2-y5-LENglOmZk',
    appId: '1:254942302329:android:edd8f73faf817461be44a8',
    messagingSenderId: '254942302329',
    projectId: 'chatapp-a7453',
    storageBucket: 'chatapp-a7453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmoWAGrvPcP21qd5Zf5AWUu3-PT_q4Dy8',
    appId: '1:254942302329:ios:3ba8d5741b91ef2ebe44a8',
    messagingSenderId: '254942302329',
    projectId: 'chatapp-a7453',
    storageBucket: 'chatapp-a7453.appspot.com',
    iosClientId: '254942302329-8vn460hc7vevmbso0h57tnu9ve165lpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.trueChatApp',
  );
}
